[features]
seeds = false
skip-lint = false
[programs.localnet]
messenger = "85oaL3HWqwwvcAYmKsyQdqgmu835Hk9eEoi6eKgYVhgK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/mort1b/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
